### ISSUE TITLE
Readme: Lock Table

### ISSUE THREAD

**Issue by simlu** [tristanls/dynamodb-lock-client#5]
No documentation on what needs to happen with the lock table. Does it need to be set up manually?

**Comment by tristanls** [comment]
Apologies,  here's a cloud formation template I use:
```yaml
AWSTemplateFormatVersion: "2010-09-09"

Resources:

  DistributedLocksStore:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits:
          Ref: DistributedLocksStoreReadCapacityUnits
        WriteCapacityUnits:
          Ref: DistributedLocksStoreWriteCapacityUnits
      TableName:
        "Fn::Join": [ "-", [ amzn, Ref: "AWS::Region", "distributed-locks-store" ] ]

Parameters:

  DistributedLocksStoreReadCapacityUnits:
    Type: Number
    Default: 1
    Description: DistributedLocksStore ReadCapacityUnits

  DistributedLocksStoreWriteCapacityUnits:
    Type: Number
    Default: 1
    Description: DistributedLocksStore WriteCapacityUnits

Outputs:

  DistributedLocksStore:
    Value:
      Fn::GetAtt: [ DistributedLocksStore, Arn ]
```
The above would make your `config.partitionKey == "id"`. It can be anything except `guid` or `owner` which are reserved (this is written down in code comment but not documented either).
